name: Terraform deploy
on:
  workflow_dispatch:
    inputs:
      docker_image_version:
        description: 'Docker image version to deploy'
        required: true
        default: 'latest'  # default value

permissions:
  id-token: write
  contents: read        

jobs:
  terraform_build:
    runs-on: ubuntu-latest
    environment:
      name: demo
    defaults:
      run:
        working-directory: './infra/terraform'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SPN_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.subscription_id }}          

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{secrets.access_key}}" -backend-config="storage_account_name=${{secrets.storage_account_name}}" -backend-config="container_name=${{secrets.container_name}}" -backend-config="key=${{ secrets.backend_key }}"
    
      - name: Terraform Apply
        id: apply 
        run: terraform apply --auto-approve -input=false -var="spn-client-id=${{secrets.SPN_CLIENT_ID}}" -var="spn-client-secret=${{secrets.SPN_CLIENT_SECRET}}" -var="spn-tenant-id=${{secrets.AZURE_TENANT_ID}}" -var="subscription-id=${{secrets.subscription_id}}" -var="openai_base_url=${{ secrets.openai_base_url }}" -var="openai_api_version=${{ secrets.openai_api_version }}" -var="openai_api_key_secret=${{ secrets.openai_api_key_secret }}" -var="docker_image_version=${{ github.event.inputs.docker_image_version }}" 
        continue-on-error: false              
